- hosts: web
  remote_user: ubuntu
  become: yes
  tasks: 
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start httpd service
      service:
        name: httpd
        state: started
    - name: copy src file
      copy: 
        src: ./index.html
        dest: /var/www/html/index.html
        mode: 0777
